[tox]
envlist = build
skipsdist = true

[testenv]
basepython = python3
passenv = *
setenv =
    CMAKE_GENERATOR=Ninja
    QT_QPA_PLATFORM=offscreen
    VCPKG_ROOT = /opt/vcpkg

allowlist_externals =
    cmake

commands =
    cmake -S . -B build \
      -DCMAKE_TOOLCHAIN_FILE={env:VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake
    cmake --build build

