[tox]
envlist = build, test, package
skipsdist = true

[testenv]
basepython = python3
passenv = *
setenv =
    CMAKE_GENERATOR=Ninja
    QT_QPA_PLATFORM=offscreen
    VCPKG_ROOT = /opt/vcpkg

allowlist_externals =
    cmake
    ctest
    watchexec
    find
    entr
    bash
    cpack

commands =
    cmake -S . -B build \
      -DCMAKE_TOOLCHAIN_FILE={env:VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake
    cmake --build build

[testenv:test]
depends = build
commands =
    ctest --test-dir build --output-on-failure

[testenv:watch]
commands =
   bash -lc 'find src qml tests CMakeLists.txt tox.ini -type f | entr -r tox -e build,test'

[testenv:package]
commands = 
   cpack --config build/CPackConfig.cmake
