
services:
  dev:
    build:
      context: .
      dockerfile: dockerfile
    tty: true
    stdin_open: true
    command: bash
    volumes:
      - ${SSH_AUTH_SOCK}:/ssh-agent
      - ..:/home/dev/workspace
    environment:
      SSH_AUTH_SOCK: /ssh-agent
