FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
   software-properties-common \
   bash \ 
   curl \
   vim \
   sudo \
   cmake

RUN add-apt-repository ppa:git-core/ppa
RUN apt-get update
RUN sudo apt-get install -y git


